/*
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.ide;


/**
 * Use this class to register ide components.
 */
public class GenerateMeIdeModule extends AbstractGenerateMeIdeModule {
}
