/*
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGenerateMeValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(uk.juliusz.generateme.generateMe.GenerateMePackage.eINSTANCE);
		return result;
	}
}
