/**
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.generateMe;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.juliusz.generateme.generateMe.Config#getBusinessName <em>Business Name</em>}</li>
 * </ul>
 *
 * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getConfig()
 * @model
 * @generated
 */
public interface Config extends EObject
{
  /**
   * Returns the value of the '<em><b>Business Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Business Name</em>' attribute.
   * @see #setBusinessName(String)
   * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getConfig_BusinessName()
   * @model
   * @generated
   */
  String getBusinessName();

  /**
   * Sets the value of the '{@link uk.juliusz.generateme.generateMe.Config#getBusinessName <em>Business Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Business Name</em>' attribute.
   * @see #getBusinessName()
   * @generated
   */
  void setBusinessName(String value);

} // Config
