/**
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.generateMe;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Content Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.juliusz.generateme.generateMe.ContentPage#getHeader <em>Header</em>}</li>
 *   <li>{@link uk.juliusz.generateme.generateMe.ContentPage#getSection <em>Section</em>}</li>
 * </ul>
 *
 * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getContentPage()
 * @model
 * @generated
 */
public interface ContentPage extends Pages
{
  /**
   * Returns the value of the '<em><b>Header</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header</em>' attribute.
   * @see #setHeader(String)
   * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getContentPage_Header()
   * @model
   * @generated
   */
  String getHeader();

  /**
   * Sets the value of the '{@link uk.juliusz.generateme.generateMe.ContentPage#getHeader <em>Header</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header</em>' attribute.
   * @see #getHeader()
   * @generated
   */
  void setHeader(String value);

  /**
   * Returns the value of the '<em><b>Section</b></em>' containment reference list.
   * The list contents are of type {@link uk.juliusz.generateme.generateMe.Section}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Section</em>' containment reference list.
   * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getContentPage_Section()
   * @model containment="true"
   * @generated
   */
  EList<Section> getSection();

} // ContentPage
