/**
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.generateMe;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contact Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.juliusz.generateme.generateMe.ContactPage#getHeader <em>Header</em>}</li>
 *   <li>{@link uk.juliusz.generateme.generateMe.ContactPage#getFrom <em>From</em>}</li>
 *   <li>{@link uk.juliusz.generateme.generateMe.ContactPage#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getContactPage()
 * @model
 * @generated
 */
public interface ContactPage extends Pages
{
  /**
   * Returns the value of the '<em><b>Header</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header</em>' attribute.
   * @see #setHeader(String)
   * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getContactPage_Header()
   * @model
   * @generated
   */
  String getHeader();

  /**
   * Sets the value of the '{@link uk.juliusz.generateme.generateMe.ContactPage#getHeader <em>Header</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header</em>' attribute.
   * @see #getHeader()
   * @generated
   */
  void setHeader(String value);

  /**
   * Returns the value of the '<em><b>From</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' attribute.
   * @see #setFrom(String)
   * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getContactPage_From()
   * @model
   * @generated
   */
  String getFrom();

  /**
   * Sets the value of the '{@link uk.juliusz.generateme.generateMe.ContactPage#getFrom <em>From</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' attribute.
   * @see #getFrom()
   * @generated
   */
  void setFrom(String value);

  /**
   * Returns the value of the '<em><b>To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' attribute.
   * @see #setTo(String)
   * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getContactPage_To()
   * @model
   * @generated
   */
  String getTo();

  /**
   * Sets the value of the '{@link uk.juliusz.generateme.generateMe.ContactPage#getTo <em>To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' attribute.
   * @see #getTo()
   * @generated
   */
  void setTo(String value);

} // ContactPage
