/**
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.generateMe;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gallery Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.juliusz.generateme.generateMe.GalleryPage#getPhotos <em>Photos</em>}</li>
 * </ul>
 *
 * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getGalleryPage()
 * @model
 * @generated
 */
public interface GalleryPage extends Pages
{
  /**
   * Returns the value of the '<em><b>Photos</b></em>' containment reference list.
   * The list contents are of type {@link uk.juliusz.generateme.generateMe.Photo}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Photos</em>' containment reference list.
   * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getGalleryPage_Photos()
   * @model containment="true"
   * @generated
   */
  EList<Photo> getPhotos();

} // GalleryPage
