/**
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.generateMe;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.juliusz.generateme.generateMe.GenerateMePackage
 * @generated
 */
public interface GenerateMeFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GenerateMeFactory eINSTANCE = uk.juliusz.generateme.generateMe.impl.GenerateMeFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Program</em>'.
   * @generated
   */
  GenerateMeProgram createGenerateMeProgram();

  /**
   * Returns a new object of class '<em>Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Config</em>'.
   * @generated
   */
  Config createConfig();

  /**
   * Returns a new object of class '<em>Home Page</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Home Page</em>'.
   * @generated
   */
  HomePage createHomePage();

  /**
   * Returns a new object of class '<em>Pages</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pages</em>'.
   * @generated
   */
  Pages createPages();

  /**
   * Returns a new object of class '<em>Content Page</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Content Page</em>'.
   * @generated
   */
  ContentPage createContentPage();

  /**
   * Returns a new object of class '<em>Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Section</em>'.
   * @generated
   */
  Section createSection();

  /**
   * Returns a new object of class '<em>Contact Page</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contact Page</em>'.
   * @generated
   */
  ContactPage createContactPage();

  /**
   * Returns a new object of class '<em>Gallery Page</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Gallery Page</em>'.
   * @generated
   */
  GalleryPage createGalleryPage();

  /**
   * Returns a new object of class '<em>Photo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Photo</em>'.
   * @generated
   */
  Photo createPhoto();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GenerateMePackage getGenerateMePackage();

} //GenerateMeFactory
