/*
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GenerateMeStandaloneSetup extends GenerateMeStandaloneSetupGenerated {

	public static void doSetup() {
		new GenerateMeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
