/*
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.juliusz.generateme.parser.antlr.internal.InternalGenerateMeParser;
import uk.juliusz.generateme.services.GenerateMeGrammarAccess;

public class GenerateMeParser extends AbstractAntlrParser {

	@Inject
	private GenerateMeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGenerateMeParser createParser(XtextTokenStream stream) {
		return new InternalGenerateMeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GenerateMeProgram";
	}

	public GenerateMeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GenerateMeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
