/*
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGenerateMeScopeProvider extends DelegatingScopeProvider {
}
