/*
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GenerateMeUiModule extends AbstractGenerateMeUiModule {

	public GenerateMeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
