/*
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.juliusz.generateme.ui.internal.GeneratemeActivator;

public class GenerateMeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GeneratemeActivator.getInstance().getInjector("uk.juliusz.generateme.GenerateMe");
	}

}
