/**
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.generateMe.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uk.juliusz.generateme.generateMe.Config;
import uk.juliusz.generateme.generateMe.GenerateMePackage;
import uk.juliusz.generateme.generateMe.GenerateMeProgram;
import uk.juliusz.generateme.generateMe.HomePage;
import uk.juliusz.generateme.generateMe.Pages;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.juliusz.generateme.generateMe.impl.GenerateMeProgramImpl#getConfig <em>Config</em>}</li>
 *   <li>{@link uk.juliusz.generateme.generateMe.impl.GenerateMeProgramImpl#getHomePage <em>Home Page</em>}</li>
 *   <li>{@link uk.juliusz.generateme.generateMe.impl.GenerateMeProgramImpl#getPages <em>Pages</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GenerateMeProgramImpl extends MinimalEObjectImpl.Container implements GenerateMeProgram
{
  /**
   * The cached value of the '{@link #getConfig() <em>Config</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConfig()
   * @generated
   * @ordered
   */
  protected Config config;

  /**
   * The cached value of the '{@link #getHomePage() <em>Home Page</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHomePage()
   * @generated
   * @ordered
   */
  protected HomePage homePage;

  /**
   * The cached value of the '{@link #getPages() <em>Pages</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPages()
   * @generated
   * @ordered
   */
  protected EList<Pages> pages;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GenerateMeProgramImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GenerateMePackage.Literals.GENERATE_ME_PROGRAM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Config getConfig()
  {
    return config;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConfig(Config newConfig, NotificationChain msgs)
  {
    Config oldConfig = config;
    config = newConfig;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GenerateMePackage.GENERATE_ME_PROGRAM__CONFIG, oldConfig, newConfig);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConfig(Config newConfig)
  {
    if (newConfig != config)
    {
      NotificationChain msgs = null;
      if (config != null)
        msgs = ((InternalEObject)config).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GenerateMePackage.GENERATE_ME_PROGRAM__CONFIG, null, msgs);
      if (newConfig != null)
        msgs = ((InternalEObject)newConfig).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GenerateMePackage.GENERATE_ME_PROGRAM__CONFIG, null, msgs);
      msgs = basicSetConfig(newConfig, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GenerateMePackage.GENERATE_ME_PROGRAM__CONFIG, newConfig, newConfig));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public HomePage getHomePage()
  {
    return homePage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetHomePage(HomePage newHomePage, NotificationChain msgs)
  {
    HomePage oldHomePage = homePage;
    homePage = newHomePage;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GenerateMePackage.GENERATE_ME_PROGRAM__HOME_PAGE, oldHomePage, newHomePage);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHomePage(HomePage newHomePage)
  {
    if (newHomePage != homePage)
    {
      NotificationChain msgs = null;
      if (homePage != null)
        msgs = ((InternalEObject)homePage).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GenerateMePackage.GENERATE_ME_PROGRAM__HOME_PAGE, null, msgs);
      if (newHomePage != null)
        msgs = ((InternalEObject)newHomePage).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GenerateMePackage.GENERATE_ME_PROGRAM__HOME_PAGE, null, msgs);
      msgs = basicSetHomePage(newHomePage, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GenerateMePackage.GENERATE_ME_PROGRAM__HOME_PAGE, newHomePage, newHomePage));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Pages> getPages()
  {
    if (pages == null)
    {
      pages = new EObjectContainmentEList<Pages>(Pages.class, this, GenerateMePackage.GENERATE_ME_PROGRAM__PAGES);
    }
    return pages;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GenerateMePackage.GENERATE_ME_PROGRAM__CONFIG:
        return basicSetConfig(null, msgs);
      case GenerateMePackage.GENERATE_ME_PROGRAM__HOME_PAGE:
        return basicSetHomePage(null, msgs);
      case GenerateMePackage.GENERATE_ME_PROGRAM__PAGES:
        return ((InternalEList<?>)getPages()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GenerateMePackage.GENERATE_ME_PROGRAM__CONFIG:
        return getConfig();
      case GenerateMePackage.GENERATE_ME_PROGRAM__HOME_PAGE:
        return getHomePage();
      case GenerateMePackage.GENERATE_ME_PROGRAM__PAGES:
        return getPages();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GenerateMePackage.GENERATE_ME_PROGRAM__CONFIG:
        setConfig((Config)newValue);
        return;
      case GenerateMePackage.GENERATE_ME_PROGRAM__HOME_PAGE:
        setHomePage((HomePage)newValue);
        return;
      case GenerateMePackage.GENERATE_ME_PROGRAM__PAGES:
        getPages().clear();
        getPages().addAll((Collection<? extends Pages>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GenerateMePackage.GENERATE_ME_PROGRAM__CONFIG:
        setConfig((Config)null);
        return;
      case GenerateMePackage.GENERATE_ME_PROGRAM__HOME_PAGE:
        setHomePage((HomePage)null);
        return;
      case GenerateMePackage.GENERATE_ME_PROGRAM__PAGES:
        getPages().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GenerateMePackage.GENERATE_ME_PROGRAM__CONFIG:
        return config != null;
      case GenerateMePackage.GENERATE_ME_PROGRAM__HOME_PAGE:
        return homePage != null;
      case GenerateMePackage.GENERATE_ME_PROGRAM__PAGES:
        return pages != null && !pages.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //GenerateMeProgramImpl
